// Code generated by js_runtime/utils/generate_ast_assets.mjs; DO NOT EDIT.
// Based on authoritative AST schema in js_runtime/src/ast_schema.json.

package ast

// IgnoreVersionMismatch controls whether AST unmarshaling validates the schema version.
// If set to true, version checking is bypassed.
var IgnoreVersionMismatch = false

// SchemaVersion defines the authoritative version of the AST schema.
const SchemaVersion = "1.2.0"

// Node represents the base interface for all nodes in the Shift Abstract Syntax Tree (AST).
type Node interface {
	NodeType() string
	GetStart() int
	GetEnd() int
	GetLine() int
}

// Statement represents an AST node that is a statement.
type Statement interface {
	Node
	stmtNode()
}

// Expression represents an AST node that evaluates to a value.
type Expression interface {
	Node
	exprNode()
}

// BaseNode implements the common positioning fields for all AST nodes.
type BaseNode struct {
	Type  string `json:"type"`
	Start int    `json:"start"`
	End   int    `json:"end"`
	Line  int    `json:"line"`
}

// NodeType returns the type name of the node.
func (b *BaseNode) NodeType() string { return b.Type }

// GetStart returns the start character index of the node in the source code.
func (b *BaseNode) GetStart() int    { return b.Start }

// GetEnd returns the end character index of the node in the source code.
func (b *BaseNode) GetEnd() int      { return b.End }

// GetLine returns the source code line number where the node begins.
func (b *BaseNode) GetLine() int     { return b.Line }

// TypeAnnotation represents a type definition or constraint, potentially including generic types.
type TypeAnnotation struct {
	Type    string          `json:"type"`
	Name    string          `json:"name"`
	Generic *TypeAnnotation `json:"generic"`
}

// StructField represents a single field declaration within a Struct.
type StructField struct {
	Name string         `json:"name"`
	Type TypeAnnotation `json:"type"`
}

// Parameter represents a parameter declaration inside a function signature.
type Parameter struct {
	Type     string         `json:"type"` // always "Parameter"
	Name     string         `json:"name"`
	DataType TypeAnnotation `json:"dataType"`
	Shared   bool           `json:"shared"`
}

// MapEntry represents a single key-value mapping within a map.
type MapEntry struct {
	Key   Expression `json:"key"`
	Value Expression `json:"value"`
}

// Program represents the AST node structure for Program.
type Program struct {
	BaseNode
	Version string `json:"version"`
	Structs []StructDeclaration `json:"structs"`
	Functions []FunctionDeclaration `json:"functions"`
}

// StructDeclaration represents the AST node structure for StructDeclaration.
type StructDeclaration struct {
	BaseNode
	Name string `json:"name"`
	Fields []StructField `json:"fields"`
}

// FunctionDeclaration represents the AST node structure for FunctionDeclaration.
type FunctionDeclaration struct {
	BaseNode
	Name string `json:"name"`
	FilePath string `json:"filePath"`
	Params []Parameter `json:"params"`
	ReturnType TypeAnnotation `json:"returnType"`
	Body *Block `json:"body"`
}

// Block represents the AST node structure for Block.
type Block struct {
	BaseNode
	Statements []Statement `json:"statements"`
}

// VariableDeclaration represents the AST node structure for VariableDeclaration.
type VariableDeclaration struct {
	BaseNode
	Name string `json:"name"`
	VarType TypeAnnotation `json:"varType"`
	Initializer Expression `json:"initializer,omitempty"`
}

// ExpressionStatement represents the AST node structure for ExpressionStatement.
type ExpressionStatement struct {
	BaseNode
	Expression Expression `json:"expression"`
}

// IfStatement represents the AST node structure for IfStatement.
type IfStatement struct {
	BaseNode
	Condition Expression `json:"condition"`
	ThenBranch *Block `json:"thenBranch"`
	ElseBranch Statement `json:"elseBranch,omitempty"`
}

// WhileStatement represents the AST node structure for WhileStatement.
type WhileStatement struct {
	BaseNode
	Condition Expression `json:"condition"`
	Body *Block `json:"body"`
}

// ForRangeStatement represents the AST node structure for ForRangeStatement.
type ForRangeStatement struct {
	BaseNode
	Iterator string `json:"iterator"`
	StartValue Expression `json:"startValue"`
	EndValue Expression `json:"endValue"`
	Body *Block `json:"body"`
}

// ForInStatement represents the AST node structure for ForInStatement.
type ForInStatement struct {
	BaseNode
	Iterator string `json:"iterator"`
	ValueIterator string `json:"valueIterator"`
	Collection Expression `json:"collection"`
	Body *Block `json:"body"`
}

// ReturnStatement represents the AST node structure for ReturnStatement.
type ReturnStatement struct {
	BaseNode
	Value Expression `json:"value,omitempty"`
}

// ThrowStatement represents the AST node structure for ThrowStatement.
type ThrowStatement struct {
	BaseNode
	Severity any `json:"severity"`
	Argument Expression `json:"argument"`
}

// TryStatement represents the AST node structure for TryStatement.
type TryStatement struct {
	BaseNode
	TryBlock *Block `json:"tryBlock"`
	CatchIdentifier string `json:"catchIdentifier"`
	CatchBlock *Block `json:"catchBlock"`
	ReviewBlock *Block `json:"reviewBlock,omitempty"`
}

// BreakStatement represents the AST node structure for BreakStatement.
type BreakStatement struct {
	BaseNode
}

// SkipStatement represents the AST node structure for SkipStatement.
type SkipStatement struct {
	BaseNode
}

// DeleteStatement represents the AST node structure for DeleteStatement.
type DeleteStatement struct {
	BaseNode
	Target *IndexExpression `json:"target"`
}

// Literal represents the AST node structure for Literal.
type Literal struct {
	BaseNode
	Value any `json:"value"`
}

// Variable represents the AST node structure for Variable.
type Variable struct {
	BaseNode
	Name string `json:"name"`
}

// MagicVariable represents the AST node structure for MagicVariable.
type MagicVariable struct {
	BaseNode
	Name string `json:"name"`
}

// Assignment represents the AST node structure for Assignment.
type Assignment struct {
	BaseNode
	Name string `json:"name"`
	Value Expression `json:"value"`
}

// IndexAssignment represents the AST node structure for IndexAssignment.
type IndexAssignment struct {
	BaseNode
	Object Expression `json:"object"`
	Index Expression `json:"index,omitempty"`
	Value Expression `json:"value"`
}

// BinaryExpression represents the AST node structure for BinaryExpression.
type BinaryExpression struct {
	BaseNode
	Operator string `json:"operator"`
	Left Expression `json:"left"`
	Right Expression `json:"right"`
}

// UnaryExpression represents the AST node structure for UnaryExpression.
type UnaryExpression struct {
	BaseNode
	Operator string `json:"operator"`
	Argument Expression `json:"argument"`
}

// PipelineExpression represents the AST node structure for PipelineExpression.
type PipelineExpression struct {
	BaseNode
	Left Expression `json:"left"`
	Right Expression `json:"right"`
}

// CallExpression represents the AST node structure for CallExpression.
type CallExpression struct {
	BaseNode
	Callee string `json:"callee"`
	Arguments []Expression `json:"arguments"`
}

// IndexExpression represents the AST node structure for IndexExpression.
type IndexExpression struct {
	BaseNode
	Object Expression `json:"object"`
	Index Expression `json:"index"`
}

// ListLiteral represents the AST node structure for ListLiteral.
type ListLiteral struct {
	BaseNode
	Elements []Expression `json:"elements"`
}

// MapLiteral represents the AST node structure for MapLiteral.
type MapLiteral struct {
	BaseNode
	Entries []MapEntry `json:"entries"`
}

// StructLiteral represents the AST node structure for StructLiteral.
type StructLiteral struct {
	BaseNode
	StructName string `json:"structName"`
	Entries []MapEntry `json:"entries"`
}

// Grouping represents the AST node structure for Grouping.
type Grouping struct {
	BaseNode
	Expression Expression `json:"expression"`
}

// CastExpression represents the AST node structure for CastExpression.
type CastExpression struct {
	BaseNode
	Value Expression `json:"value"`
	TargetType TypeAnnotation `json:"targetType"`
}

// InspectExpression represents the AST node structure for InspectExpression.
type InspectExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// PackExpression represents the AST node structure for PackExpression.
type PackExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// UnpackExpression represents the AST node structure for UnpackExpression.
type UnpackExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// SizeOfExpression represents the AST node structure for SizeOfExpression.
type SizeOfExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// TypeOfExpression represents the AST node structure for TypeOfExpression.
type TypeOfExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// IsExpression represents the AST node structure for IsExpression.
type IsExpression struct {
	BaseNode
	Left Expression `json:"left"`
	Check string `json:"check"`
	IsNot bool `json:"isNot"`
}

// ReplaceExpression represents the AST node structure for ReplaceExpression.
type ReplaceExpression struct {
	BaseNode
	Source Expression `json:"source"`
	Pattern Expression `json:"pattern"`
	Replacement Expression `json:"replacement"`
}

// SplitExpression represents the AST node structure for SplitExpression.
type SplitExpression struct {
	BaseNode
	Source Expression `json:"source"`
	Delimiter Expression `json:"delimiter"`
}

// JoinExpression represents the AST node structure for JoinExpression.
type JoinExpression struct {
	BaseNode
	Source Expression `json:"source"`
	Delimiter Expression `json:"delimiter"`
}

// TransferStatement represents the AST node structure for TransferStatement.
type TransferStatement struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// ShareExpression represents the AST node structure for ShareExpression.
type ShareExpression struct {
	BaseNode
	Argument Expression `json:"argument"`
}

// Marker methods for statements
func (*VariableDeclaration) stmtNode() {}
func (*ReturnStatement) stmtNode() {}
func (*TransferStatement) stmtNode() {}
func (*IfStatement) stmtNode() {}
func (*WhileStatement) stmtNode() {}
func (*ForRangeStatement) stmtNode() {}
func (*ForInStatement) stmtNode() {}
func (*BreakStatement) stmtNode() {}
func (*SkipStatement) stmtNode() {}
func (*TryStatement) stmtNode() {}
func (*ThrowStatement) stmtNode() {}
func (*DeleteStatement) stmtNode() {}
func (*ExpressionStatement) stmtNode() {}
func (*Block) stmtNode() {}

// Marker methods for expressions
func (*Assignment) exprNode() {}
func (*IndexAssignment) exprNode() {}
func (*PipelineExpression) exprNode() {}
func (*ShareExpression) exprNode() {}
func (*BinaryExpression) exprNode() {}
func (*UnaryExpression) exprNode() {}
func (*CallExpression) exprNode() {}
func (*IndexExpression) exprNode() {}
func (*CastExpression) exprNode() {}
func (*InspectExpression) exprNode() {}
func (*PackExpression) exprNode() {}
func (*UnpackExpression) exprNode() {}
func (*SizeOfExpression) exprNode() {}
func (*TypeOfExpression) exprNode() {}
func (*IsExpression) exprNode() {}
func (*ReplaceExpression) exprNode() {}
func (*SplitExpression) exprNode() {}
func (*JoinExpression) exprNode() {}
func (*Literal) exprNode() {}
func (*Variable) exprNode() {}
func (*MagicVariable) exprNode() {}
func (*ListLiteral) exprNode() {}
func (*MapLiteral) exprNode() {}
func (*StructLiteral) exprNode() {}
func (*Grouping) exprNode() {}
