// Code generated by js_runtime/utils/generate_ast_assets.mjs; DO NOT EDIT.
// Based on authoritative AST schema in js_runtime/src/ast_schema.json.

package ast

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// StatementWrapper wraps a Statement interface for custom JSON unmarshaling.
type StatementWrapper struct {
	Statement Statement
}

// UnmarshalJSON implements json.Unmarshaler for StatementWrapper.
func (sw *StatementWrapper) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) {
		sw.Statement = nil
		return nil
	}

	var typeHelper struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &typeHelper); err != nil {
		return err
	}

	var stmt Statement
	switch typeHelper.Type {
	case "VariableDeclaration":
		var v VariableDeclaration
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "ReturnStatement":
		var v ReturnStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "IfStatement":
		var v IfStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "WhileStatement":
		var v WhileStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "ForRangeStatement":
		var v ForRangeStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "ForInStatement":
		var v ForInStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "BreakStatement":
		var v BreakStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "SkipStatement":
		var v SkipStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "TryStatement":
		var v TryStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "ThrowStatement":
		var v ThrowStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "DeleteStatement":
		var v DeleteStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "ExpressionStatement":
		var v ExpressionStatement
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	case "Block":
		var v Block
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
	default:
		return fmt.Errorf("unknown statement type: %s", typeHelper.Type)
	}

	sw.Statement = stmt
	return nil
}

// ExpressionWrapper wraps an Expression interface for custom JSON unmarshaling.
type ExpressionWrapper struct {
	Expression Expression
}

// UnmarshalJSON implements json.Unmarshaler for ExpressionWrapper.
func (ew *ExpressionWrapper) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) {
		ew.Expression = nil
		return nil
	}

	var typeHelper struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &typeHelper); err != nil {
		return err
	}

	var expr Expression
	switch typeHelper.Type {
	case "Assignment":
		var v Assignment
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "IndexAssignment":
		var v IndexAssignment
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "PipelineExpression":
		var v PipelineExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "BinaryExpression":
		var v BinaryExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "UnaryExpression":
		var v UnaryExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "CallExpression":
		var v CallExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "IndexExpression":
		var v IndexExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "CastExpression":
		var v CastExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "InspectExpression":
		var v InspectExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "PackExpression":
		var v PackExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "UnpackExpression":
		var v UnpackExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "SizeOfExpression":
		var v SizeOfExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "TypeOfExpression":
		var v TypeOfExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "IsExpression":
		var v IsExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "ReplaceExpression":
		var v ReplaceExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "SplitExpression":
		var v SplitExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "JoinExpression":
		var v JoinExpression
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "Literal":
		var v Literal
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "Variable":
		var v Variable
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "MagicVariable":
		var v MagicVariable
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "ListLiteral":
		var v ListLiteral
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "MapLiteral":
		var v MapLiteral
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	case "Grouping":
		var v Grouping
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
	default:
		return fmt.Errorf("unknown expression type: %s", typeHelper.Type)
	}

	ew.Expression = expr
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for Block.
func (n *Block) UnmarshalJSON(data []byte) error {
	type Alias Block
	var aux struct {
		Statements []StatementWrapper `json:"statements"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Statements = make([]Statement, len(aux.Statements))
	for i, w := range aux.Statements {
		n.Statements[i] = w.Statement
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for VariableDeclaration.
func (n *VariableDeclaration) UnmarshalJSON(data []byte) error {
	type Alias VariableDeclaration
	var aux struct {
		Initializer ExpressionWrapper `json:"initializer"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Initializer = aux.Initializer.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ExpressionStatement.
func (n *ExpressionStatement) UnmarshalJSON(data []byte) error {
	type Alias ExpressionStatement
	var aux struct {
		Expression ExpressionWrapper `json:"expression"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Expression = aux.Expression.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for IfStatement.
func (n *IfStatement) UnmarshalJSON(data []byte) error {
	type Alias IfStatement
	var aux struct {
		Condition ExpressionWrapper `json:"condition"`
		ElseBranch StatementWrapper `json:"elseBranch"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Condition = aux.Condition.Expression
	n.ElseBranch = aux.ElseBranch.Statement
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for WhileStatement.
func (n *WhileStatement) UnmarshalJSON(data []byte) error {
	type Alias WhileStatement
	var aux struct {
		Condition ExpressionWrapper `json:"condition"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Condition = aux.Condition.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ForRangeStatement.
func (n *ForRangeStatement) UnmarshalJSON(data []byte) error {
	type Alias ForRangeStatement
	var aux struct {
		StartValue ExpressionWrapper `json:"startValue"`
		EndValue ExpressionWrapper `json:"endValue"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.StartValue = aux.StartValue.Expression
	n.EndValue = aux.EndValue.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ForInStatement.
func (n *ForInStatement) UnmarshalJSON(data []byte) error {
	type Alias ForInStatement
	var aux struct {
		Collection ExpressionWrapper `json:"collection"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Collection = aux.Collection.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ReturnStatement.
func (n *ReturnStatement) UnmarshalJSON(data []byte) error {
	type Alias ReturnStatement
	var aux struct {
		Value ExpressionWrapper `json:"value"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Value = aux.Value.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ThrowStatement.
func (n *ThrowStatement) UnmarshalJSON(data []byte) error {
	type Alias ThrowStatement
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for Assignment.
func (n *Assignment) UnmarshalJSON(data []byte) error {
	type Alias Assignment
	var aux struct {
		Value ExpressionWrapper `json:"value"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Value = aux.Value.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for IndexAssignment.
func (n *IndexAssignment) UnmarshalJSON(data []byte) error {
	type Alias IndexAssignment
	var aux struct {
		Object ExpressionWrapper `json:"object"`
		Index ExpressionWrapper `json:"index"`
		Value ExpressionWrapper `json:"value"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Object = aux.Object.Expression
	n.Index = aux.Index.Expression
	n.Value = aux.Value.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for BinaryExpression.
func (n *BinaryExpression) UnmarshalJSON(data []byte) error {
	type Alias BinaryExpression
	var aux struct {
		Left ExpressionWrapper `json:"left"`
		Right ExpressionWrapper `json:"right"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Left = aux.Left.Expression
	n.Right = aux.Right.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for UnaryExpression.
func (n *UnaryExpression) UnmarshalJSON(data []byte) error {
	type Alias UnaryExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for PipelineExpression.
func (n *PipelineExpression) UnmarshalJSON(data []byte) error {
	type Alias PipelineExpression
	var aux struct {
		Left ExpressionWrapper `json:"left"`
		Right ExpressionWrapper `json:"right"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Left = aux.Left.Expression
	n.Right = aux.Right.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for CallExpression.
func (n *CallExpression) UnmarshalJSON(data []byte) error {
	type Alias CallExpression
	var aux struct {
		Arguments []ExpressionWrapper `json:"arguments"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Arguments = make([]Expression, len(aux.Arguments))
	for i, w := range aux.Arguments {
		n.Arguments[i] = w.Expression
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for IndexExpression.
func (n *IndexExpression) UnmarshalJSON(data []byte) error {
	type Alias IndexExpression
	var aux struct {
		Object ExpressionWrapper `json:"object"`
		Index ExpressionWrapper `json:"index"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Object = aux.Object.Expression
	n.Index = aux.Index.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ListLiteral.
func (n *ListLiteral) UnmarshalJSON(data []byte) error {
	type Alias ListLiteral
	var aux struct {
		Elements []ExpressionWrapper `json:"elements"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Elements = make([]Expression, len(aux.Elements))
	for i, w := range aux.Elements {
		n.Elements[i] = w.Expression
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for Grouping.
func (n *Grouping) UnmarshalJSON(data []byte) error {
	type Alias Grouping
	var aux struct {
		Expression ExpressionWrapper `json:"expression"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Expression = aux.Expression.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for CastExpression.
func (n *CastExpression) UnmarshalJSON(data []byte) error {
	type Alias CastExpression
	var aux struct {
		Value ExpressionWrapper `json:"value"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Value = aux.Value.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for InspectExpression.
func (n *InspectExpression) UnmarshalJSON(data []byte) error {
	type Alias InspectExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for PackExpression.
func (n *PackExpression) UnmarshalJSON(data []byte) error {
	type Alias PackExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for UnpackExpression.
func (n *UnpackExpression) UnmarshalJSON(data []byte) error {
	type Alias UnpackExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for SizeOfExpression.
func (n *SizeOfExpression) UnmarshalJSON(data []byte) error {
	type Alias SizeOfExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for TypeOfExpression.
func (n *TypeOfExpression) UnmarshalJSON(data []byte) error {
	type Alias TypeOfExpression
	var aux struct {
		Argument ExpressionWrapper `json:"argument"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Argument = aux.Argument.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for IsExpression.
func (n *IsExpression) UnmarshalJSON(data []byte) error {
	type Alias IsExpression
	var aux struct {
		Left ExpressionWrapper `json:"left"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Left = aux.Left.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for ReplaceExpression.
func (n *ReplaceExpression) UnmarshalJSON(data []byte) error {
	type Alias ReplaceExpression
	var aux struct {
		Source ExpressionWrapper `json:"source"`
		Pattern ExpressionWrapper `json:"pattern"`
		Replacement ExpressionWrapper `json:"replacement"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Source = aux.Source.Expression
	n.Pattern = aux.Pattern.Expression
	n.Replacement = aux.Replacement.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for SplitExpression.
func (n *SplitExpression) UnmarshalJSON(data []byte) error {
	type Alias SplitExpression
	var aux struct {
		Source ExpressionWrapper `json:"source"`
		Delimiter ExpressionWrapper `json:"delimiter"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Source = aux.Source.Expression
	n.Delimiter = aux.Delimiter.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for JoinExpression.
func (n *JoinExpression) UnmarshalJSON(data []byte) error {
	type Alias JoinExpression
	var aux struct {
		Source ExpressionWrapper `json:"source"`
		Delimiter ExpressionWrapper `json:"delimiter"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Source = aux.Source.Expression
	n.Delimiter = aux.Delimiter.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for MapEntry.
func (n *MapEntry) UnmarshalJSON(data []byte) error {
	type Alias MapEntry
	var aux struct {
		Key ExpressionWrapper `json:"key"`
		Value ExpressionWrapper `json:"value"`
		*Alias
	}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	n.Key = aux.Key.Expression
	n.Value = aux.Value.Expression
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for Program.
// It verifies that the JSON contains the required "version" field matching "1.0.0",
// unless IgnoreVersionMismatch is set to true.
func (p *Program) UnmarshalJSON(data []byte) error {
	type Alias Program
	var aux struct {
		*Alias
	}
	aux.Alias = (*Alias)(p)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	if !IgnoreVersionMismatch {
		if p.Version == "" {
			return fmt.Errorf("Schema Error: AST is missing version metadata")
		}
		if p.Version != "1.0.0" {
			return fmt.Errorf("Schema Error: Unsupported AST schema version: '%s'. Expected '1.0.0'.", p.Version)
		}
	}
	return nil
}
