import fs from 'fs';
import path from 'path';

const WORKSPACE_DIR = '.';
const SCHEMA_PATH = path.join(WORKSPACE_DIR, 'js_runtime/src/ast_schema.json');
const AST_GO_PATH = path.join(WORKSPACE_DIR, 'go_runtime/pkg/ast/ast.go');
const UNMARSHAL_GO_PATH = path.join(WORKSPACE_DIR, 'go_runtime/pkg/ast/unmarshal.go');
const DOCS_PATH = path.join(WORKSPACE_DIR, 'docs/6_ast_specification.md');

// Load schema
const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
const definitions = schema.definitions;

// Helper to check if a definition is a statement or expression
const statementTypes = [...definitions.Statement.oneOf.map(x => x.$ref.split('/').pop()), 'Block'];
const expressionTypes = definitions.Expression.oneOf.map(x => x.$ref.split('/').pop());

function getGoType(propSchema, parentName, propName) {
    if (propSchema.$ref) {
        const refName = propSchema.$ref.split('/').pop();
        if (refName === 'Statement' || refName === 'Expression') {
            return refName;
        }
        if (refName === 'Block' || refName === 'IndexExpression' || refName === parentName) {
            return '*' + refName;
        }
        if (refName === 'TypeAnnotation') {
            return 'TypeAnnotation';
        }
        return '*' + refName; // fallback for other concrete structs
    }

    if (propSchema.oneOf) {
        const nonNulls = propSchema.oneOf.filter(x => x.type !== 'null');
        if (nonNulls.length === 1) {
            const innerType = getGoType(nonNulls[0], parentName, propName);
            // Block inside TryStatement reviewBlock should be *Block
            if (nonNulls[0].$ref && nonNulls[0].$ref.split('/').pop() === 'Block' && !innerType.startsWith('*')) {
                return '*' + innerType;
            }
            return innerType;
        }
        // Check if all non-nulls are statements or expressions
        const refNames = nonNulls.map(x => x.$ref ? x.$ref.split('/').pop() : null);
        if (refNames.every(name => name && statementTypes.includes(name))) {
            return 'Statement';
        }
        if (refNames.every(name => name && expressionTypes.includes(name))) {
            return 'Expression';
        }
        return 'any';
    }

    if (propSchema.type === 'array') {
        const items = propSchema.items;
        if (items.$ref) {
            const refName = items.$ref.split('/').pop();
            return '[]' + refName;
        }
        // Handle inline helper structs
        if (parentName === 'StructDeclaration' && propName === 'fields') {
            return '[]StructField';
        }
        if (parentName === 'FunctionDeclaration' && propName === 'params') {
            return '[]Parameter';
        }
        if ((parentName === 'MapLiteral' || parentName === 'StructLiteral') && propName === 'entries') {
            return '[]MapEntry';
        }
        return '[]any';
    }

    if (Array.isArray(propSchema.type)) {
        const types = propSchema.type.filter(t => t !== 'null');
        if (types.length === 1) {
            const t = types[0];
            if (t === 'string') return 'string';
            if (t === 'integer') return 'int';
            if (t === 'boolean') return 'bool';
            if (t === 'number') return 'float64';
        }
        return 'any';
    }

    switch (propSchema.type) {
        case 'string': return 'string';
        case 'integer': return 'int';
        case 'boolean': return 'bool';
        case 'number': return 'float64';
        default: return 'any';
    }
}

// ----------------------------------------------------
// Generate go_runtime/pkg/ast/ast.go
// ----------------------------------------------------
function generateAstGo() {
    let code = `// Code generated by js_runtime/utils/generate_ast_assets.mjs; DO NOT EDIT.
// Based on authoritative AST schema in js_runtime/src/ast_schema.json.

package ast

// IgnoreVersionMismatch controls whether AST unmarshaling validates the schema version.
// If set to true, version checking is bypassed.
var IgnoreVersionMismatch = false

// SchemaVersion defines the authoritative version of the AST schema.
const SchemaVersion = "${schema.version}"

// Node represents the base interface for all nodes in the Shift Abstract Syntax Tree (AST).
type Node interface {
	NodeType() string
	GetStart() int
	GetEnd() int
	GetLine() int
}

// Statement represents an AST node that is a statement.
type Statement interface {
	Node
	stmtNode()
}

// Expression represents an AST node that evaluates to a value.
type Expression interface {
	Node
	exprNode()
}

// BaseNode implements the common positioning fields for all AST nodes.
type BaseNode struct {
	Type  string \`json:"type"\`
	Start int    \`json:"start"\`
	End   int    \`json:"end"\`
	Line  int    \`json:"line"\`
}

// NodeType returns the type name of the node.
func (b *BaseNode) NodeType() string { return b.Type }

// GetStart returns the start character index of the node in the source code.
func (b *BaseNode) GetStart() int    { return b.Start }

// GetEnd returns the end character index of the node in the source code.
func (b *BaseNode) GetEnd() int      { return b.End }

// GetLine returns the source code line number where the node begins.
func (b *BaseNode) GetLine() int     { return b.Line }
`;

    // Add inline helpers
    code += `
// TypeAnnotation represents a type definition or constraint, potentially including generic types.
type TypeAnnotation struct {
	Type    string          \`json:"type"\`
	Name    string          \`json:"name"\`
	Generic *TypeAnnotation \`json:"generic"\`
}

// StructField represents a single field declaration within a Struct.
type StructField struct {
	Name string         \`json:"name"\`
	Type TypeAnnotation \`json:"type"\`
}

// Parameter represents a parameter declaration inside a function signature.
type Parameter struct {
	Type     string         \`json:"type"\` // always "Parameter"
	Name     string         \`json:"name"\`
	DataType TypeAnnotation \`json:"dataType"\`
	Shared   bool           \`json:"shared"\`
}

// MapEntry represents a single key-value mapping within a map.
type MapEntry struct {
	Key   Expression \`json:"key"\`
	Value Expression \`json:"value"\`
}
`;

    // Generate concrete structs
    for (const [name, def] of Object.entries(definitions)) {
        if (name === 'Node' || name === 'Statement' || name === 'Expression' || name === 'TypeAnnotation') {
            continue;
        }

        // Find properties
        let properties = {};
        let embedsBaseNode = false;

        if (def.allOf) {
            embedsBaseNode = def.allOf.some(x => x.$ref === '#/definitions/Node');
            const propDef = def.allOf.find(x => x.properties);
            if (propDef) {
                properties = propDef.properties;
            }
        } else if (def.properties) {
            properties = def.properties;
        }

        code += `\n// ${name} represents the AST node structure for ${name}.\n`;
        code += `type ${name} struct {\n`;
        if (embedsBaseNode) {
            code += `\tBaseNode\n`;
        }



        for (const [propName, propSchema] of Object.entries(properties)) {
            if (propName === 'type' && embedsBaseNode) {
                // inherited from BaseNode
                continue;
            }

            const goType = getGoType(propSchema, name, propName);
            const camelName = propName.charAt(0).toUpperCase() + propName.slice(1);

            // Check if field is optional/nullable
            const isOptional = propSchema.oneOf && propSchema.oneOf.some(x => x.type === 'null');
            const jsonTag = `\`json:"${propName}${isOptional ? ',omitempty' : ''}"\``;

            code += `\t${camelName} ${goType} ${jsonTag}\n`;
        }
        code += `}\n`;
    }

    // Add marker methods for Statement and Expression implementations
    code += `\n// Marker methods for statements\n`;
    for (const name of statementTypes) {
        code += `func (*${name}) stmtNode() {}\n`;
    }

    code += `\n// Marker methods for expressions\n`;
    for (const name of expressionTypes) {
        code += `func (*${name}) exprNode() {}\n`;
    }

    fs.writeFileSync(AST_GO_PATH, code, 'utf8');
    console.log(`Generated: ${AST_GO_PATH}`);
}

// ----------------------------------------------------
// Generate go_runtime/pkg/ast/unmarshal.go
// ----------------------------------------------------
function generateUnmarshalGo() {
    let code = `// Code generated by js_runtime/utils/generate_ast_assets.mjs; DO NOT EDIT.
// Based on authoritative AST schema in js_runtime/src/ast_schema.json.

package ast

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// StatementWrapper wraps a Statement interface for custom JSON unmarshaling.
type StatementWrapper struct {
	Statement Statement
}

// UnmarshalJSON implements json.Unmarshaler for StatementWrapper.
func (sw *StatementWrapper) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) {
		sw.Statement = nil
		return nil
	}

	var typeHelper struct {
		Type string \`json:"type"\`
	}
	if err := json.Unmarshal(data, &typeHelper); err != nil {
		return err
	}

	var stmt Statement
	switch typeHelper.Type {
`;

    for (const name of statementTypes) {
        code += `\tcase "${name}":
		var v ${name}
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		stmt = &v
`;
    }

    code += `\tdefault:
		return fmt.Errorf("unknown statement type: %s", typeHelper.Type)
	}

	sw.Statement = stmt
	return nil
}

// ExpressionWrapper wraps an Expression interface for custom JSON unmarshaling.
type ExpressionWrapper struct {
	Expression Expression
}

// UnmarshalJSON implements json.Unmarshaler for ExpressionWrapper.
func (ew *ExpressionWrapper) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, []byte("null")) {
		ew.Expression = nil
		return nil
	}

	var typeHelper struct {
		Type string \`json:"type"\`
	}
	if err := json.Unmarshal(data, &typeHelper); err != nil {
		return err
	}

	var expr Expression
	switch typeHelper.Type {
`;

    for (const name of expressionTypes) {
        code += `\tcase "${name}":
		var v ${name}
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		expr = &v
`;
    }

    code += `\tdefault:
		return fmt.Errorf("unknown expression type: %s", typeHelper.Type)
	}

	ew.Expression = expr
	return nil
}
`;

    // Helper to determine if a type requires a custom unmarshaler
    function isInterfaceOrInterfaceList(goType) {
        return goType === 'Statement' || goType === 'Expression' || goType === '[]Statement' || goType === '[]Expression';
    }

    // Custom unmarshalers for concrete structs containing interfaces
    const structNames = Object.keys(definitions).filter(n => n !== 'Node' && n !== 'Statement' && n !== 'Expression' && n !== 'TypeAnnotation');

    // Add inline helpers as they also need unmarshaling if they contain interfaces
    structNames.push('MapEntry');

    for (const name of structNames) {
        // Find properties
        let properties = {};
        if (name === 'MapEntry') {
            properties = {
                key: { $ref: '#/definitions/Expression' },
                value: { $ref: '#/definitions/Expression' }
            };
        } else {
            const def = definitions[name];
            if (def.allOf) {
                const propDef = def.allOf.find(x => x.properties);
                if (propDef) properties = propDef.properties;
            } else if (def.properties) {
                properties = def.properties;
            }
        }

        // Check if we have any fields that are Statement or Expression (or lists of them)
        const wrapperFields = [];
        for (const [propName, propSchema] of Object.entries(properties)) {
            const goType = getGoType(propSchema, name, propName);
            if (isInterfaceOrInterfaceList(goType)) {
                wrapperFields.push({
                    name: propName,
                    camelName: propName.charAt(0).toUpperCase() + propName.slice(1),
                    goType: goType
                });
            }
        }

        if (wrapperFields.length === 0) {
            continue;
        }

        code += `
// UnmarshalJSON implements json.Unmarshaler for ${name}.
func (n *${name}) UnmarshalJSON(data []byte) error {
	type Alias ${name}
	var aux struct {
`;

        for (const field of wrapperFields) {
            const wrapperType = field.goType.replace('Statement', 'StatementWrapper').replace('Expression', 'ExpressionWrapper');
            code += `\t\t${field.camelName} ${wrapperType} \`json:"${field.name}"\`\n`;
        }

        code += `\t\t*Alias\n\t}
	aux.Alias = (*Alias)(n)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
`;

        for (const field of wrapperFields) {
            if (field.goType.startsWith('[]')) {
                const innerType = field.goType.slice(2); // Statement or Expression
                code += `\tn.${field.camelName} = make([]${innerType}, len(aux.${field.camelName}))
	for i, w := range aux.${field.camelName} {
		n.${field.camelName}[i] = w.${innerType}
	}
`;
            } else {
                code += `\tn.${field.camelName} = aux.${field.camelName}.${field.goType}\n`;
            }
        }

        code += `	return nil\n}\n`;
    }

    // Add Program custom unmarshaler for version checking
    code += `
// UnmarshalJSON implements json.Unmarshaler for Program.
// It verifies that the JSON contains the required "version" field matching "${schema.version}",
// unless IgnoreVersionMismatch is set to true.
func (p *Program) UnmarshalJSON(data []byte) error {
	type Alias Program
	var aux struct {
		*Alias
	}
	aux.Alias = (*Alias)(p)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	if !IgnoreVersionMismatch {
		if p.Version == "" {
			return fmt.Errorf("Schema Error: AST is missing version metadata")
		}
		if p.Version != "${schema.version}" {
			return fmt.Errorf("Schema Error: Unsupported AST schema version: '%s'. Expected '${schema.version}'.", p.Version)
		}
	}
	return nil
}
`;

    fs.writeFileSync(UNMARSHAL_GO_PATH, code, 'utf8');
    console.log(`Generated: ${UNMARSHAL_GO_PATH}`);
}

// ----------------------------------------------------
// Generate ast_specification.md
// ----------------------------------------------------
function generateAstDocs() {
    let md = `# Shift AST Specification

This document defines the schema and structure of the Shift Abstract Syntax Tree (AST), also known as the Shift Tree (\`.stree\`). 

The AST serves as the portable, language-independent intermediate representation of Shift programs. Both the Go and JavaScript interpreters execute this JSON structure directly.

---

## 1. Common Node Fields

Every node in the AST extends the basic node structure, containing positional markers for debugging and error reporting:

| Field | Type | Description |
|---|---|---|
| \`type\` | \`string\` | The node type identifier (e.g., \`"Program"\`, \`"IfStatement"\`, etc.). |
| \`start\` | \`number\` | The starting character offset in the source script. |
| \`end\` | \`number\` | The ending character offset in the source script. |
| \`line\` | \`number\` | The 1-indexed source code line number where this node begins. |

---

## 2. Structural Schema

### Program
The root node representing a parsed Shift file.
\`\`\`json
{
  "type": "Program",
  "start": 0,
  "end": 120,
  "line": 1,
  "structs": [],
  "functions": []
}
\`\`\`

### TypeAnnotation
Represents a type declaration inside parameters, returns, and variables. In the AST, it has type \`"Type"\` for primitives and generic collections, or \`"StructType"\` for custom struct references.

#### Standard Type Annotation
\`\`\`json
{
  "type": "Type",
  "name": "list",
  "generic": {
    "type": "Type",
    "name": "number"
  }
}
\`\`\`

#### Struct Type Annotation
\`\`\`json
{
  "type": "StructType",
  "name": "User"
}
\`\`\`

### StructDeclaration
Declares a new data structure.
\`\`\`json
{
  "type": "StructDeclaration",
  "name": "User",
  "fields": [
    {
      "name": "id",
      "type": { "type": "StructType", "name": "User" }
    }
  ]
}
\`\`\`

### FunctionDeclaration
Declares a global function.
\`\`\`json
{
  "type": "FunctionDeclaration",
  "name": "add",
  "params": [
    {
      "type": "Parameter",
      "name": "x",
      "dataType": { "type": "Type", "name": "number" }
    }
  ],
  "returnType": { "type": "Type", "name": "number" },
  "body": {
    "type": "Block",
    "statements": []
  }
}
\`\`\`

---

## 3. Statements

Statements represent execution operations and do not evaluate to values.

### VariableDeclaration
Declares a block-scoped variable.
\`\`\`json
{
  "type": "VariableDeclaration",
  "name": "count",
  "varType": { "type": "Type", "name": "number" },
  "initializer": { "type": "Literal", "value": 0 }
}
\`\`\`

### IfStatement
\`\`\`json
{
  "type": "IfStatement",
  "condition": { "type": "Variable", "name": "flag" },
  "thenBranch": { "type": "Block", "statements": [] },
  "elseBranch": { "type": "Block", "statements": [] } // Optional, can be IfStatement or Block
}
\`\`\`

### WhileStatement
\`\`\`json
{
  "type": "WhileStatement",
  "condition": { "type": "BinaryExpression", "operator": "<", ... },
  "body": { "type": "Block", "statements": [] }
}
\`\`\`

### ForRangeStatement
Loop syntax: \`for (i in 0 to 10)\`
\`\`\`json
{
  "type": "ForRangeStatement",
  "iterator": "i",
  "startValue": { "type": "Literal", "value": 0 },
  "endValue": { "type": "Literal", "value": 10 },
  "body": { "type": "Block", "statements": [] }
}
\`\`\`

### ForInStatement
Loop syntax: \`for (key, value in my_map)\` or \`for (item in my_list)\`
\`\`\`json
{
  "type": "ForInStatement",
  "iterator": "key",
  "valueIterator": "value", // Optional (only for map key-value loops)
  "collection": { "type": "Variable", "name": "my_map" },
  "body": { "type": "Block", "statements": [] }
}
\`\`\`

### TryStatement
Error handling block: \`try { ... } catch { ... } review { ... }\`
\`\`\`json
{
  "type": "TryStatement",
  "tryBlock": { "type": "Block", "statements": [] },
  "catchIdentifier": "err",
  "catchBlock": { "type": "Block", "statements": [] },
  "reviewBlock": { "type": "Block", "statements": [] } // Optional
}
\`\`\`

### Other Statements
`;

    // Dynamically list statement details from schema
    for (const name of statementTypes) {
        if (['VariableDeclaration', 'IfStatement', 'WhileStatement', 'ForRangeStatement', 'ForInStatement', 'TryStatement'].includes(name)) {
            continue; // covered in details above
        }

        // Find fields
        const def = definitions[name];
        let fields = [];
        let properties = {};
        if (def.allOf) {
            const propDef = def.allOf.find(x => x.properties);
            if (propDef) properties = propDef.properties;
        } else if (def.properties) {
            properties = def.properties;
        }

        for (const [propName, propSchema] of Object.entries(properties)) {
            if (propName === 'type') continue;
            const goType = getGoType(propSchema, name, propName);
            fields.push(`\`${propName}: ${goType}\``);
        }

        md += `- **${name}**: \`{ "type": "${name}"${fields.length > 0 ? ', ' + fields.join(', ') : ''} }\`\n`;
    }

    md += `
---

## 4. Expressions

Expressions represent computations that yield values.

| Type | Fields | Description / Examples |
|---|---|---|
`;

    // Helper descriptions for expressions to populate in Section 4 table
    const exprDetails = {
        'Literal': { syntax: '\`value: any\`', desc: '\`42\`, \`"hello"\`, \`true\`, \`null\`' },
        'Variable': { syntax: '\`name: string\`', desc: '\`my_var\`' },
        'MagicVariable': { syntax: '\`name: string\`', desc: '\`$pipe_value\`, \`$thrown_message\`' },
        'Assignment': { syntax: '\`name: string\`, \`value: Expression\`', desc: '\`x = 5\`' },
        'IndexAssignment': { syntax: '\`object: Expression\`, \`index: Expression\`, \`value: Expression\`', desc: '\`arr[0] = 5\`' },
        'BinaryExpression': { syntax: '\`operator: string\`, \`left: Expression\`, \`right: Expression\`', desc: '\`x + y\`, \`a and b\`' },
        'UnaryExpression': { syntax: '\`operator: string\`, \`argument: Expression\`', desc: '\`not flag\`, \`-num\`' },
        'PipelineExpression': { syntax: '\`left: Expression\`, \`right: Expression\`', desc: '\`data \\| process($pipe_value)\`' },
        'CallExpression': { syntax: '\`callee: string\`, \`arguments: []Expression\`', desc: '\`print_line("hello")\`' },
        'IndexExpression': { syntax: '\`object: Expression\`, \`index: Expression\`', desc: '\`map["key"]\`, \`arr[0]\`' },
        'CastExpression': { syntax: '\`value: Expression\`, \`targetType: TypeAnnotation\`', desc: '\`5 as string\`' },
        'InspectExpression': { syntax: '\`argument: Expression\`', desc: '\`inspect my_var\`' },
        'SizeOfExpression': { syntax: '\`argument: Expression\`', desc: '\`size of my_var\`' },
        'TypeOfExpression': { syntax: '\`argument: Expression\`', desc: '\`type of my_var\`' },
        'PackExpression': { syntax: '\`argument: Expression\`', desc: '\`pack my_list\`' },
        'UnpackExpression': { syntax: '\`argument: Expression\`', desc: '\`unpack my_string\`' },
        'IsExpression': { syntax: '\`left: Expression\`, \`check: string\`, \`isNot: bool\`', desc: '\`str is numeric\`' },
        'ReplaceExpression': { syntax: '\`source: Expression\`, \`pattern: Expression\`, \`replacement: Expression\`', desc: '\`str replace "/regex/" with ""\`' },
        'SplitExpression': { syntax: '\`source: Expression\`, \`delimiter: Expression\`', desc: '\`str split with ","\`' },
        'JoinExpression': { syntax: '\`source: Expression\`, \`delimiter: Expression\`', desc: '\`arr joined with ","\`' },
        'ListLiteral': { syntax: '\`elements: []Expression\`', desc: '\`[1, 2, 3]\`' },
        'MapLiteral': { syntax: '\`entries: []MapEntry\`', desc: '\`["key": "value"]\`' },
        'StructLiteral': { syntax: '\`structName: string\`, \`entries: []MapEntry\`', desc: '\`User ["name": "Tom"]\`' },
        'Grouping': { syntax: '\`expression: Expression\`', desc: '\`(x + y)\`' }
    };

    // Dynamically list all expressions from schema, ensuring none are missed
    for (const name of expressionTypes) {
        const detail = exprDetails[name];
        if (detail) {
            md += `| **${name}** | ${detail.syntax} | ${detail.desc} |\n`;
        } else {
            // Find fields as fallback
            const def = definitions[name];
            let fields = [];
            let properties = {};
            if (def.allOf) {
                const propDef = def.allOf.find(x => x.properties);
                if (propDef) properties = propDef.properties;
            } else if (def.properties) {
                properties = def.properties;
            }
            for (const [propName, propSchema] of Object.entries(properties)) {
                if (propName === 'type') continue;
                const goType = getGoType(propSchema, name, propName);
                fields.push(`\`${propName}: ${goType}\``);
            }
            md += `| **${name}** | ${fields.join(', ')} | (Auto-generated entry) |\n`;
        }
    }

    md += `
---

## 5. Compiled Example

Here is a simple Shift script and its resulting JSON AST:

### Source Script
\`\`\`shift
function main() number {
    number result = 40 + 2;
    return result;
}
\`\`\`

### JSON AST (\`Program\`)
\`\`\`json
{
  "type": "Program",
  "start": 0,
  "end": 74,
  "line": 1,
  "structs": [],
  "functions": [
    {
      "type": "FunctionDeclaration",
      "start": 0,
      "end": 74,
      "line": 1,
      "name": "main",
      "params": [],
      "returnType": {
        "type": "Type",
        "name": "number"
      },
      "body": {
        "type": "Block",
        "start": 23,
        "end": 74,
        "line": 1,
        "statements": [
          {
            "type": "VariableDeclaration",
            "start": 29,
            "end": 51,
            "line": 2,
            "name": "result",
            "varType": {
              "type": "Type",
              "name": "number"
            },
            "initializer": {
              "type": "BinaryExpression",
              "start": 45,
              "end": 51,
              "line": 2,
              "operator": "+",
              "left": {
                "type": "Literal",
                "start": 45,
                "end": 47,
                "line": 2,
                "value": 40
              },
              "right": {
                "type": "Literal",
                "start": 50,
                "end": 51,
                "line": 2,
                "value": 2
              }
            }
          },
          {
            "type": "ReturnStatement",
            "start": 57,
            "end": 72,
            "line": 3,
            "value": {
              "type": "Variable",
              "start": 64,
              "end": 70,
              "line": 3,
              "name": "result"
            }
          }
        ]
      }
    }
  ]
}
\`\`\`
`;

    fs.writeFileSync(DOCS_PATH, md, 'utf8');
    console.log(`Generated: ${DOCS_PATH}`);
}

// Run generators
generateAstGo();
generateUnmarshalGo();
generateAstDocs();
console.log('All AST assets generated successfully.');
